<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\YtDlpGui.Core\YtDlpGui.Core.csproj" />
    <ProjectReference Include="..\YtDlpGui.Services\YtDlpGui.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PropertyChanged.Fody" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
