<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <RootNamespace>YtDlpGui.WPF</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <ApplicationIcon>Resources\logo.ico</ApplicationIcon>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <TrimMode>copyused</TrimMode>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="System.Collections" />
    <TrimmerRootAssembly Include="System.Runtime" />
    <TrimmerRootAssembly Include="System.Runtime.Extensions" />
    <TrimmerRootAssembly Include="System.Runtime.InteropServices" />
    <TrimmerRootAssembly Include="System.Runtime.CompilerServices.VisualC" />
  </ItemGroup>
  
  <ItemGroup>
    <None Remove="Resources\logo.ico" />
    <None Remove="Resources\xshd\desc.xshd" />
    <None Remove="Resources\xshd\url.xshd" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\logo.ico" />
    <Resource Include="Resources\xshd\desc.xshd" />
    <Resource Include="Resources\xshd\url.xshd">
      <CustomToolNamespace></CustomToolNamespace>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="MdXaml_migfree" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="PropertyChanged.Fody" />
    <PackageReference Include="SharpClipboard" />
    <PackageReference Include="Swordfish.NET.CollectionsV3" />
    <PackageReference Include="System.Resources.ResourceManager" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YtDlpGui.Core\YtDlpGui.Core.csproj" />
    <ProjectReference Include="..\YtDlpGui.Services\YtDlpGui.Services.csproj" />
    <ProjectReference Include="..\YtDlpGui.ViewModels\YtDlpGui.ViewModels.csproj" />
  </ItemGroup>

</Project>
