<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swordfish.NET.CollectionsV3" Version="3.3.12" />
    <PackageReference Include="YamlDotNet" Version="13.0.2" />
  </ItemGroup>

</Project>
